In [3]:
##usually the images will be stored in terms of pixels
##to do this we use numpy
import numpy as np
n=np.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [4]:
##2d array
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
##3d array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
##to convert lists to array
ary=np.asarray([[1,2,3],[5,6,7],[8,9,45]])
print(ary)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 45]]


In [16]:
ar=np.asarray([[1,2,3],[],[]])
print(ar)

[list([1, 2, 3]) list([]) list([])]


In [17]:
type(ar)

numpy.ndarray